version: 1
jobs:
  build:
    image: node
    script:
      - npm install truffle
      - npm install
      - ./node_modules/.bin/truffle compile
      - ./node_modules/.bin/truffle test
  test:
    image: node
    script:
      - npm install truffle
      - npm install
      - ./node_modules/.bin/truffle compile
      - ./node_modules/.bin/truffle test

stages:
  - build_and_test:
      jobs:
        - build
        - test
