version: 1
jobs:
  build:
    image: node
    when: manual
    script:
      - npm install truffle
      - npm install
      - ./node_modules/.bin/truffle compile
      - ./node_modules/.bin/truffle test
  test:
    type:
      name: 'ethereum/deploy'
      signing: true
      record: true
    services:
      - name: strm/helloworld-http
        alias: hello
    image: 'alpine:3.10'
    script:
      - apk add curl
      - curl http://hello

stages:
  - just_build:
      jobs:
        - build
        - test
