version: 1
jobs:
  patata job:
    image: node
    script:
      - npm install truffle
      - npm install
      - ./node_modules/.bin/truffle compile
      - ./node_modules/.bin/truffle test
    branch: master
