version: 1
jobs:
  build:
    image: node
    script:
      - npm install truffle
      - npm install
      - ./node_modules/.bin/truffle compile
      - ./node_modules/.bin/truffle test
  test:
    image: alpine
    services:
      - name: superblocks/variables-decoder
        alias: variables-decoder
    script:
      - apk add curl
      - eval "$(curl -X POST 'http://variables-decoder/decode-vars' -H 'Content-Type:text/plain' --data-binary @super_env_variables.txt)"
      - echo vars are $Q, $Q1, $Q2
  
stages:
  - just_build:
      jobs:
        - build
        - test
